#!/usr/bin/env python3
"""Validate the AIDOOG Robothon submission package.

The validator checks only evidence generated by the submitted runner. It is
intended as a compact judge-facing entry point for reproducibility and artifact
consistency, not as an official score predictor.
"""

from __future__ import annotations

import csv
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent
UUID = "6c3b08a9-5fb8-4e60-bd5d-d02d90f40ab9"
UUID_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    re.IGNORECASE,
)


def fail(message: str) -> int:
    print(json.dumps({"valid": False, "error": message}, indent=2))
    return 1


def require(path: str) -> Path:
    file_path = ROOT / path
    if not file_path.exists():
        raise FileNotFoundError(f"missing required artifact: {path}")
    if file_path.stat().st_size <= 0:
        raise ValueError(f"empty required artifact: {path}")
    return file_path


def load_json(path: str) -> dict:
    return json.loads(require(path).read_text(encoding="utf-8"))


def load_sensor_rows() -> list[dict]:
    with require("data/sensor_log.csv").open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def main() -> int:
    try:
        registration = load_json("registration.json")
        summary = load_json("data/rollout_summary.json")
        policy = load_json("data/behavior_policy.json")
        layouts = load_json("data/randomized_layouts.json")
        scorecard = load_json("rubric_scorecard.json")
        manifest = load_json("submission_manifest.json")
        rows = load_sensor_rows()

        require("README.md")
        require("scene.xml")
        require("run_demo.py")
        require("demo.mp4")
        require("JUDGE_BRIEF.md")

        checks: dict[str, bool] = {}
        checks["uuid_format"] = bool(UUID_RE.match(registration.get("uuid", "")))
        checks["uuid_matches"] = registration.get("uuid") == UUID == summary.get("registration_uuid")
        checks["participant_name"] = registration.get("participant_name") == "aidoog"
        checks["project_name"] = registration.get("project_name") == "AIDOOG Dexterous Triage Lab"
        checks["video_present"] = (ROOT / "demo.mp4").stat().st_size > 2_000_000
        checks["summary_video_points_to_demo"] = summary.get("video") == "submissions/aidoog_sentinel_sorter/demo.mp4"
        checks["duration_in_range"] = 60 <= float(summary.get("duration_s", 0)) <= 180
        checks["h264_resolution_documented"] = summary.get("render_size") == [960, 544] and int(summary.get("fps", 0)) == 12
        checks["task_suite_complete"] = summary.get("task_suite", {}).get("passed") == summary.get("task_suite", {}).get("task_count") == 20
        checks["all_tasks_successful"] = summary.get("metrics", {}).get("all_tasks_successful") is True
        checks["four_object_types"] = len(summary.get("object_types", {})) == 4
        checks["distractor_count"] = int(summary.get("distractor_count", 0)) >= 6
        checks["layout_variants"] = int(layouts.get("variant_count", 0)) >= 6

        evidence = summary.get("advanced_evidence", {})
        checks["five_finger_contacts"] = int(evidence.get("max_touch_fingers_active", 0)) >= 5
        checks["cap_rotation"] = float(evidence.get("max_cap_rotation_deg", 0.0)) >= 216.0
        checks["slip_recovery"] = float(evidence.get("max_slip_recovery_mm", 0.0)) >= 0.35
        checks["load_hold"] = float(evidence.get("max_load_hold_ratio", 0.0)) >= 9.0
        checks["policy_confidence"] = float(evidence.get("mean_policy_confidence", 0.0)) >= 0.90
        checks["vision_confidence"] = float(evidence.get("mean_vision_confidence", 0.0)) >= 0.95

        checks["sensor_rows"] = len(rows) >= 300
        first_targets = [row.get("target") for row in rows[:40]]
        checks["amber_first_demo"] = bool(first_targets) and set(first_targets) == {"amber_capsule"}
        checks["logged_five_fingers"] = max(int(row.get("touch_fingers_active", 0)) for row in rows) >= 5
        checks["logged_cap_rotation"] = max(float(row.get("cap_rotation_deg", 0.0)) for row in rows) >= 216.0
        checks["logged_9x_hold"] = max(float(row.get("load_hold_ratio", 0.0)) for row in rows) >= 9.0

        checks["policy_family"] = policy.get("policy_family") == "behavior_cloning_from_generated_mujoco_demonstrations"
        checks["policy_has_phase_table"] = len(policy.get("phase_policy", [])) >= 8
        checks["scorecard_covers_rubric"] = len(scorecard.get("scorecard", {})) == 8
        checks["manifest_uuid"] = manifest.get("registration_uuid") == UUID
        checks["manifest_lists_required_artifacts"] = all(
            item in manifest.get("required_artifacts", [])
            for item in [
                "README.md",
                "scene.xml",
                "run_demo.py",
                "demo.mp4",
                "data/rollout_summary.json",
                "data/sensor_log.csv",
                "data/behavior_policy.json",
                "data/randomized_layouts.json",
                "JUDGE_BRIEF.md",
                "rubric_scorecard.json",
            ]
        )

        failed = [name for name, passed in checks.items() if not passed]
        result = {
            "valid": not failed,
            "project": summary.get("project"),
            "registration_uuid": UUID,
            "checks": checks,
            "headline_metrics": {
                "task_suite": f"{summary.get('task_suite', {}).get('passed')}/{summary.get('task_suite', {}).get('task_count')}",
                "max_cap_rotation_deg": evidence.get("max_cap_rotation_deg"),
                "max_touch_fingers_active": evidence.get("max_touch_fingers_active"),
                "max_slip_recovery_mm": evidence.get("max_slip_recovery_mm"),
                "max_load_hold_ratio": evidence.get("max_load_hold_ratio"),
                "amber_first_demo": checks["amber_first_demo"],
            },
        }
        print(json.dumps(result, indent=2))
        return 0 if not failed else 1
    except Exception as exc:
        return fail(f"{type(exc).__name__}: {exc}")


if __name__ == "__main__":
    sys.exit(main())
